### ISSUE TITLE
Unable to install TSExact extension

### ISSUE THREAD

**Issue by waqaraziz123** [alistairewj/reproducibility-mimic#2]
Hi, 
I am trying to install TSExact extension on PSQL 10.1 but unable to do so. Can you please give a hint on how to install it for windows 10?

Thanks

**Comment by alistairewj** [comment]
Unfortunately the TSExact extension isn't updated to work with psql 10.1. This is probably because most of the functionality is now a part of core postgres. The code should probably be updated to work with postgres 9.6+ and I'll see if I can find time to do that in the coming weeks.

**Comment by waqaraziz123** [comment]
Thank you.

**Comment by waqaraziz123** [comment]
Hi Alistair,
Any luck with this extension work?

Thanks

**Comment by alistairewj** [comment]
It's been very busy on my side, but I've finally managed to remove the need for the extension. The results may change imperceptibly - instead of counting the absolute number of stop words, it sums the number of distinct stop words per note, and aggregates by admissions. This is used to remove patients in one study which required patients who have at least 100 non-stop words or more, so the consequence of this is we may exclude an additional 1-10 patients, unlikely to have a huge effect but worth noting.
